name: Cortex Code Review

on:
  push:
    branches:
      - main        # triggers on merge to main
  schedule:
    - cron: '0 0 * * *'   # runs every day at midnight
  
jobs:
  cortex-review:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: jyothsnalade/cortex-action@v1  #uses: {owner}/{repo}@{tag}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          console-url: https://console.pervaziv.com
